// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRr5o_0Jkx8BmBxBOqkqSFPkwMpIkupw',
    appId: '1:7341965061:web:d39ab3d6ab92730268016c',
    messagingSenderId: '7341965061',
    projectId: 'madaction-aeaea',
    authDomain: 'madaction-aeaea.firebaseapp.com',
    storageBucket: 'madaction-aeaea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY8dMIXwNVKblOTxDyx3x0IxepOkdGvos',
    appId: '1:7341965061:android:43c166afb1bb4bd568016c',
    messagingSenderId: '7341965061',
    projectId: 'madaction-aeaea',
    storageBucket: 'madaction-aeaea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpanLO0IMyAHSTylek_ReBDs14yMsWdQ',
    appId: '1:7341965061:ios:db9c377937cb3d8e68016c',
    messagingSenderId: '7341965061',
    projectId: 'madaction-aeaea',
    storageBucket: 'madaction-aeaea.firebasestorage.app',
    iosClientId: '7341965061-jbqlcc6ss5j14o5a0457joakf398u9ca.apps.googleusercontent.com',
    iosBundleId: 'dev.andriarosarmelle.madaurore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUpanLO0IMyAHSTylek_ReBDs14yMsWdQ',
    appId: '1:7341965061:ios:db9c377937cb3d8e68016c',
    messagingSenderId: '7341965061',
    projectId: 'madaction-aeaea',
    storageBucket: 'madaction-aeaea.firebasestorage.app',
    iosClientId: '7341965061-jbqlcc6ss5j14o5a0457joakf398u9ca.apps.googleusercontent.com',
    iosBundleId: 'dev.andriarosarmelle.madaurore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXRr5o_0Jkx8BmBxBOqkqSFPkwMpIkupw',
    appId: '1:7341965061:web:0b4209f94aaf290968016c',
    messagingSenderId: '7341965061',
    projectId: 'madaction-aeaea',
    authDomain: 'madaction-aeaea.firebaseapp.com',
    storageBucket: 'madaction-aeaea.firebasestorage.app',
  );

}